# Generated by Django 2.0.6 on 2021-02-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackClicksApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
