# Generated by Django 2.0.6 on 2021-02-06 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StackClicksApp', '0002_auto_20210206_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='referee',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
