# Generated by Django 2.0.6 on 2021-02-12 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StackClicksApp', '0005_auto_20210206_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('package', models.CharField(choices=[('S', 'Silver'), ('P', 'Platinum'), ('R', 'Ruby'), ('S', 'Star'), ('G', 'Gold Star'), ('O', 'Opal'), ('D', 'Diamond'), ('M', 'Premium')], max_length=1)),
            ],
            options={
                'verbose_name': 'Payment',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='VendorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('whatsapp_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Successful')], default='P', max_length=1)),
                ('type', models.CharField(choices=[('B', 'Balance'), ('R', 'Referral')], max_length=1)),
                ('processed', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'ordering': ['-created_on'],
            },
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'verbose_name': 'Task'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'User'},
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='account_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='account_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bank_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='referral_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TransactionModel',
        ),
        migrations.AddField(
            model_name='withdrawalrequestmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
