# Generated by Django 2.0.6 on 2021-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackClicksApp', '0006_auto_20210212_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='referral_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
