# Generated by Django 2.0.6 on 2021-02-15 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StackClicksApp', '0007_auto_20210313_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('package', models.CharField(choices=[('S', 'Silver'), ('P', 'Platinum'), ('R', 'Ruby'), ('S', 'Star'), ('G', 'Gold Star'), ('O', 'Opal'), ('D', 'Diamond'), ('M', 'Premium')], max_length=1)),
                ('used', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StackClicksApp.VendorModel')),
            ],
        ),
    ]
