# Generated by Django 2.0.6 on 2021-02-18 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackClicksApp', '0008_couponmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='couponmodel',
            options={'verbose_name': 'Coupon'},
        ),
        migrations.AlterModelOptions(
            name='vendormodel',
            options={'verbose_name': 'Vendor'},
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='completed_by',
            field=models.ManyToManyField(editable=False, related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
