# Generated by Django 2.0.6 on 2021-02-18 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StackClicksApp', '0009_auto_20210218_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ['-created_on'], 'verbose_name': 'Message'},
        ),
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'ordering': ['-created_on'], 'verbose_name': 'Task'},
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
