# Generated by Django 2.0.6 on 2021-02-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackClicksApp', '0011_auto_20210220_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='number',
            field=models.CharField(editable=False, max_length=16, unique=True),
        ),
    ]
