# Generated by Django 2.0.6 on 2021-02-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackClicksApp', '0012_auto_20210220_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='number',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
